version: "3.5"

services:
  postgres:
    container_name: postgres-my-mountains
    image: postgres:14.5
    restart: always
    ports:
      - 8432:5432
    networks:
      - database
    volumes:
      - postgres-my-mountains:/var/lib/postgresql/data
      - ./conf/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: "Europe/Rome"
      PGTZ: "Europe/Rome"

networks:
  database:
    name: database

volumes:
  postgres-my-mountains:
    name: postgres-my-mountains
